### PR TITLE
update 06_packages 30_differential_abundance book.bib

### PR DESCRIPTION
**Pull request by chloelulu**
I have made the following revisions:
- I included descriptions of the "Examples and tools" section, taking a statistical learning perspective.
- Based on my own analysis experience, I added some currently popular tools to the list. 
- Additionally, I added demo functions of ZicoSeq, which we proposed in my Microbiome paper. Based on my evaluation of current tools and our current clinical collaborations, I am confident of its FDR control and power. This increased the number of demo tools to 5, and I adjusted the "Comparison of the methods" section accordingly.
- I also included some descriptions of "confounding variables", which I believe will be of great interest to users.
- Corresponding part in "06_packages.Rmd" and "book.bib" has been updated.
- I am contemplating expanding the chapter to cover "longitudinal analysis", but the current version does not include it. If appropriate, I am glad to include this in the next version.

### CODE REVIEW

**Comment by antagomir** [comment]
Thanks!

The automated build fails with

Quitting from lines 471-527 (30_differential_abundance.Rmd) 
Error in robust_plots[[1]] : subscript out of bounds

Have you checked that you can render the book without error in R with:

`bookdown::render_book()`

You can also view with:

`bookdown::serve_book()`

**Comment by antagomir** [comment]
-> If possible, update the PR so that the issue is fixed? Or if you need support/advice let us know.

**Comment by chloelulu** [comment]
Sorry for the late reply. Just got some time on the weekend to fix this. Just now I tried bookdown::render_book(), but it got an error and stopped with the error shown below. Could be the package version difference of miaViz? I also tried the knit the html file to my local with my current code 30_differential_abundance.Rmd, there is no error. Could you give me some suggestions in fix this? Thanks. 

processing file: 12_quality_control.Rmd
  |......                                       |  14% (unnamed-chunk-2)       Quitting from lines 38-53 (12_quality_control.Rmd) 
Error in .density_plotter(density_data = density_data, layout = layout,  : 
  unused arguments (assay_name = "relabundance", point_alpha = 0.1)
Calls: local ... plotAbundanceDensity -> plotAbundanceDensity -> .local
In addition: Warning message:
replacing previous import 'mia::left_join' by 'dplyr::left_join' when loading 'miaViz' 
                                                                                                                   
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 12_quality_control.Rmd

**Comment by antagomir** [comment]
I think this is related to the latest Bioconductor version update, which happened last week.

Change `assay_name` to `assay.type` in the code.

Make sure you pull changes from the current microbiome/OMA main branch as well, in order to avoid git conflicts.

You can upgrade to R-4.3.0 and install the latest Bioconductor release version if necessary but it might work already without this if you have sufficiently new package versions in use.

**Comment by chloelulu** [comment]
> Thanks!
> 
> The automated build fails with
> 
> Quitting from lines 471-527 (30_differential_abundance.Rmd) Error in robust_plots[[1]] : subscript out of bounds
> 
> Have you checked that you can render the book without error in R with:
> 
> `bookdown::render_book()`
> 
> You can also view with:
> 
> `bookdown::serve_book()`

I encountered issues when attempting to execute bookdown::render_book() on both of my computers. One of my computers is outdated and cannot be updated to R version 4.3.0, while the other is a Mac with an M2 chip that does not support the installation of mia's dependent package, densvis. 
However, upon further investigation, I discovered that the error could be caused by a discrepancy in the ANCOMBC version. The newer ANCOMBC v2.0.3 (which I recently updated to) produces output that differs from the previous version, ANCOMBC v1.2.2, that I had used. I suspect that GitHub automatically checks for the usage of v2.0+, which caused the failure with an empty plot[[1]].

**Comment by antagomir** [comment]
I have now updated the main branch and this issue (causing failure) was solved in another PR, let's see if it goes through now after syncing with the master branch.

**Comment by antagomir** [comment]
Ok, we got forward at least. Not sure about the new error. 

If you could pull the latest version from master branch and check that the book renders locally, then push, let's see. If it still doesn't work we can see what to do.

**Comment by chloelulu** [comment]
1. Correct the "Error: Failed to build the bibliography via bibtex”, which could be caused by having duplicated entry of Zhou2022 in both the LinDA paper and fastANCOM paper short title.
2. Remove duplication in the reference for ANCOMBC. Initially, the book.bib file contained two references for ANCOMBC - Das2022 and ancombc2022. I removed the Das2022 citation in 30_differential_abundance_analysis.Rmd and updated it consistently to ancombc2022.
3. Modify the citation titles of some articles to avoid potential conflicts in the future, and reformat some references’ author names into Last name + First name format.
4. Restructure the presentation of statistical difficulties for better clarity and understanding.
I hope that this time it will pass the check. :-)

**Comment by chloelulu** [comment]
The error in the Kumar2018 reference may have resulted from the improper formatting of the author names, which I have now rectified. Replace comma into "and".

**Comment by antagomir** [comment]
Whoa - it is a pass - thanks!!!

**Comment by chloelulu** [comment]
> Whoa - it is a pass - thanks!!!

Nice! Cheers!

**Pull request merged**
