### PR TITLE
Added front page figure

### PR DESCRIPTION
**Pull request by TuomasBorman**
Hi,

I like Leo's idea of front page figure so I implemented it. 

Here are two different versions, another has figure before title and another after. Which is better? I think after is better, and in this current implementation it is after. 

Any thoughts from others, should we add this?

Before:
image

After (current implementation):
image

Issue: https://github.com/microbiome/OMA/issues/63

-Tuomas

### CODE REVIEW

**Comment by antagomir** [comment]
I also vote for the latter. Thanks!

**Comment by antagomir** [comment]
Hmm just one note - would it be possible to remove the ML4microbiome logo from the top left corner e.g. with an image manipulation program? We are associated with that COST action but I would not tie the whole book with it.

**Comment by TuomasBorman** [comment]
OK, I can do that

**Comment by ChouaibB** [comment]
After seems perfect.

**Comment by TuomasBorman** [comment]
Removed 

image

**Comment by antagomir** [comment]
so nice

**Review by ChouaibB — APPROVED** [review]

**Pull request merged**
