### PR TITLE
Work on aesthetics of the book

### PR DESCRIPTION
**Pull request by AxelDgn**
Here is a first view of the book, trying to follow Leo's instructions.
I improvised a bit with the banner if you have any ideas I'm open to suggestions. 
Let me know what you think.

OMA view 2 png
OMA view

### CODE REVIEW

**Comment by antagomir** [comment]
It looks promising. 

For me (Ubuntu + Chromium) the logo and header are overlapping. 

Logo is also having different, lighter color than usually - it gives a less sharp impression.

R and Bioc version could be just black text (not red, like now)

**Comment by antagomir** [comment]
Is more in the making?

**Comment by TuomasBorman** [comment]
Looks very nice!! Is the coloring of mia logo changed or does it just look like it?

**Comment by AxelDgn** [comment]
> Is more in the making?

Hello, I found a new color palette that complements the main color of the Mia logo, and I fixed some display bugs. The display on Firefox and Edge looks correct; let me know if it's good for you too. 
I just need to fix a few things before committing the changes here, but here's an overview :

image
Palette OMA

**Comment by TuomasBorman** [comment]
I liked the previous one more (but if the mia logo could be with original colors)

**Comment by antagomir** [comment]
YEs looks nice!

One thing I spotted and we might like to think about is the position of the references. The second TOC in right margin is a bit unnecessary but also references are handily shown on the right margin just next to the text and it would also have space for other margin notes (like footnotes). In the new version not I think. Should/could we consider that right margin can still be there but margins (both left and right) could be optionally folded out when the reader wants to have more space on the actual text? Or what should do on that..

**Comment by AxelDgn** [comment]
> YEs looks nice!
> 
> One thing I spotted and we might like to think about is the position of the references. The second TOC in right margin is a bit unnecessary but also references are handily shown on the right margin just next to the text and it would also have space for other margin notes (like footnotes). In the new version not I think. Should/could we consider that right margin can still be there but margins (both left and right) could be optionally folded out when the reader wants to have more space on the actual text? Or what should

I think the left margin should stay in place, but I can check if we can add the right margin for references by adding a fold option


> I liked the previous one more (but if the mia logo could be with original colors)

I'll try to add the original logo, but this banner is a PNG image, so I was having trouble managing the CSS to make it sharp when displayed

**Comment by AxelDgn** [comment]
Here is an example of what can be added in the margin : https://quarto.org/docs/blog/posts/2022-02-17-advanced-layout/

**Comment by antagomir** [comment]
Great - I like to possibilty to keep both margins but it might be helpful to provide folding option for margin/s if this is not too difficult to achieve.

**Comment by antagomir** [comment]
@TuomasBorman shall we merge?

**Comment by TuomasBorman** [comment]
What is the layout currently? Can you paste some pictures?

**Review by TuomasBorman — APPROVED** [review]

**Comment by TuomasBorman** [comment]
@antagomir 

I checked the layout and it is the green/yellow one. I liked the blue one more. Do you have any preferences?

**Comment by TuomasBorman** [comment]
But one thing to check if we decide to go with blue one, is the banner figure. --> Is it freely available?

**Comment by antagomir** [comment]
Blue is ok to me.

**Comment by AxelDgn** [comment]
image

Here is the current layout, last blue banner was not free to use.

**Comment by antagomir** [comment]
Is there is something still ongoing @AxelDgn

**Comment by antagomir** [comment]
@TuomasBorman has approved. Can we merge?

**Comment by TuomasBorman** [comment]
We can try to find free figure for that later (I think it looked very nice), but I think this is good to go now

**Comment by TuomasBorman** [comment]
ONe option is to try generative AI tools

**Pull request merged**
