### PR TITLE
Update reproducible reporting and outreach

### PR DESCRIPTION
**Pull request by RiboRings**
Hi! I moved the reproducible reporting section from course webpage to OMA. Something was already in OMA, so I just modified it. I also added outreach section in resources chapter with quarto presentations.

### CODE REVIEW

**Comment by antagomir** [comment]
Seems very good.

**Review by antagomir — COMMENTED** [review]
Can you check issue #238 and update accordingly.

Also possible to update the other parts in the same way for the same PR

**Comment by RiboRings** [comment]
> Can you check issue #238 and update accordingly.
> 
> Also possible to update the other parts in the same way for the same PR

The problem is that without
`if(!require(GUniFrac)){
  install.packages("GUniFrac")
}`

an import error arises. Or am I missing something?

**Comment by antagomir** [comment]
If that really is the case then no problem to have it.

I just wonder how common that is.

My default solution would be to add this in [.github/workflows](https://github.com/microbiome/OMA/blob/master/.github/workflows/build-book-release.yml) that describes the OMA conversion. I can see that GUnifrac is already there so I am not sure what the problem is. 

Ok we can merge in this case as this passes otherwise. We can continue to troubleshoot issue #238 separately. 

Thanks!

**Pull request merged**
