### PR TITLE
Update 19_visualization_techniques.Rmd

### PR DESCRIPTION
**Pull request by Elina297**
Sorry, not a really usefull contribution again but I had to test one more time

### CODE REVIEW

**Review by antagomir — APPROVED** [review]
Great. 

Just to check, have you noticed that contributions to OMA are not eligible for Outreachy? Contributions to the R packages (mia, miaViz, miaTime, miaSim) are.

**Comment by Elina297** [comment]
Sorry I'm not sure to understand. So apparently no I didn't notice. Does it mean that I actually can contribute only to the coding part of the book ? I don't know what is Outreachy and I have access only to OMA so I don't really understand how I can contribute to the R packages, it's a bit confusing for me. envoyé : 14 mars 2023 à 12:39de : Leo Lahti ***@***.***>à : microbiome/OMA ***@***.***>cc : Elina297 ***@***.***>, Author ***@***.***>objet : Re: [microbiome/OMA] Update 19_visualization_techniques.Rmd (PR ***@***.*** approved this pull request.Great.Just to check, have you noticed that contributions to OMA are not eligible for Outreachy? Contributions to the R packages (mia, miaViz, miaTime, miaSim) are.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by antagomir** [comment]
Hi @Elina297 - some contributors are right now coming through an open source initiative called Outreachy. If you are not part of that, there are no limitations. All contributions are very welcome.

**Comment by antagomir** [comment]
We have approved and merged this one.

**Pull request merged**
