### PR TITLE
Delete duplicate lines

### PR DESCRIPTION
**Pull request by RiboRings**
Hi!

I noticed that in [PERMANOVA comparison](https://microbiome.github.io/OMA/extras.html#permanova-comparison) section there are some duplicate lines, so I deleted them.

Just in case if you could double check.
Cheers!

### CODE REVIEW

**Review by antagomir — COMMENTED** [review]
The covariates seem to be in different order in the "duplicate" examples, so the duplicates are not identical. Does the order influence p-values in this case? If yes, then at least a note should be added mentioning that the order of covariates affects the outcome.

**Comment by RiboRings** [comment]
Could you give me a hint how to use `as.function`?

I tried the following inside a for-loop, where my_grid$Var1 are all the combinations of explanatory variables, and my_grid$Var2 are all the `by` arguments.

```
 my_ad <- adonis2(formula = as.function(paste0('t(assay(enterotype, "relabundance")) ~ ', my_grid$Var1[idx])), 
                   by = as.character(my_grid$Var2[idx]),
                   data = colData(enterotype),
                   permutations = 99)
           
```

I get the error: `Error in as.function.default(paste0("t(assay(enterotype, \"relabundance\")) ~ ",  : 
  list argument expected`

**Comment by RiboRings** [comment]
Never mind, it seems to work with `as.formula`

**Review by antagomir — APPROVED** [review]

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
Unnamed chunk causes some error. 

Could you add names for the chunks, and see if the error could be spotted..?

**Comment by RiboRings** [comment]
Yes, thanks for the clue!

**Comment by antagomir** [comment]
Awesome!

**Pull request merged**
