### PR TITLE
Conversion to BiocBook

### PR DESCRIPTION
**Pull request by js2264**
Hi OMA authors,

Following my issue https://github.com/microbiome/OMA/issues/375, I have initiated some work to convert the OMA book to a `BiocBook` infrastructure [see [here](https://github.com/js2264/BiocBook) for some details].

Few points worth bringing up:

- The pages are now in `.qmd` (quarto) format, and located in `inst/index.qmd` and `inst/pages/*qmd`. You can add any page to the book by creating a new `.qmd` file in `inst/pages/` and reference this file in the `inst/assets/_book.yml` listing.
I have copied and pasted most of the pages content, and made very minor changes (such as fixing the reference calls).
- This PR should actually be merged to a new`devel` branch on the `microbiome/OMA` repo, not the `master` I currently selected (but I cannot directly create this branch in your repo). This would allow automatic detection of the Bioc version to use: a branch named `devel` (or `RELEASE_3_18`) will use bioc `devel` (or bioc `3.18`) to build the book (and deploy it to `gh-pages:docs/3.18`). The `master` branch is not going to trigger automated book building at all.
- If you want to serve the book from the github repository, the Pages settings should be set to serve Pages from the `gh-pages` branch (root folder). An automated redirection sends to `gh-pages:docs/devel`, but can be set up to other versions (if any `RELEASE_*` branch exists). The URL that points to an actual book (once generated) would be https://microbiome.github.io/OMA/docs/devel/ (or https://microbiome.github.io/OMA/docs/RELEASE_*/).
- The repo can be installed with `remotes::install_github("js2264/OMA")`, which sets up all the dependencies from CRAN/Bioc (and `miaTime` from github). Alternatively, a docker image with pre-configured RStudio server is available (`docker pull ghcr.io/js2264/oma:devel`). Once the PR pulled, this would become `microbiome/OMA` of course.

Let me know if there is anything unclear. The automated website (only on Bioc devel for now) is available here: [https://js2264.github.io/OMA/docs/devel/](https://js2264.github.io/OMA/docs/devel/). I have opened this PR to check how changed files would show up. Feel free to postpone the review until ready, I mostly wanted to have it open so my fork (`devel` branch) can be directly compared to your `master`.

### CODE REVIEW

**Review by TuomasBorman — APPROVED** [review]
Hi, sorry for the delay. I think this looks good! I believe this is ready to be merged?

-Tuomas

**Comment by js2264** [comment]
Hi @TuomasBorman, If the authors are OK editing qmd files in inst/pages/ instead of Rmd files in /, yes the merge is ready.
Is it OK though if I do little changes here and there to clarify how to edit pages, render the book locally, how it is rendered by GitHub, etc, before the PR is merged?

**Comment by antagomir** [comment]
Is OK and please check that README would contain instructions on how to use this, for instance is there a way to render and view locally etc. basic info so that developers will find this easily.

**Comment by js2264** [comment]
I have updated the README to reflect this @antagomir.

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
Just to check - are the new network chapters 60/61 included from the recently merged PR #303 

            "60_network_learning.Rmd",
            "61_network_comparison.Rmd",

I do not see these in the PR

**Comment by antagomir** [comment]
Could you sync with the upstream master branch to make sure we are sync with all the latest updates?

**Comment by js2264** [comment]
No they are not, I just noticed the commit! I'll sync my `devel` with your `master` and update this current PR.

**Comment by js2264** [comment]
The 2 new chapters are now included as `qmd` files in the `inst/pages/` folder. The book is being rebuilt in my fork (https://github.com/js2264/OMA), it takes ~2h to build. Locally, things look good. I'll ping you when the build is green in my fork.

**Comment by antagomir** [comment]
Seems to override #374

**Comment by antagomir** [comment]
@TuomasBorman is there still something pending on this, or could we merge?

**Comment by TuomasBorman** [comment]
Yes, I think we can merge this. But let's merge this to master and develop master branch instead of devel for now? --> Because master does not trigger automated build, let's keep devel branch synced with master

In spring when this book is more ready let's switch using devel branch as it should be used

**Comment by antagomir** [comment]
I merged accidentally to devel branch (not master as agreed) and then reverted.

@js2264 could you create the PR against the master branch?

**Comment by js2264** [comment]
@antagomir I'll create a new PR asap. In the meantime, FYI the merge did trigger the `biocbook` github workflow, which is still running. When it finishes, it will commit/push to the `gh-pages`, so you may want to abort this before it finishes!

**Pull request merged**
