### PR TITLE
Book fixes and clean-up.

### PR DESCRIPTION
**Pull request by ChouaibB**
In the following fixes were made related to issue #52.
* Files renamed
* Fixing alpha and beta sections as were supposed to be separate.
* Added session info to alpha diversity section.
* Moved the interactive 3D plot section before bibliography.

### CODE REVIEW

**Comment by TuomasBorman** [comment]
Thanks! Overall, I think the book looks nice. 

One thing: Should `Interactive 3D plots` be a subchapter of e.g., `Extras` chapter? If there will be more these extra stuffs, then again, I think the structure of book is not that coherent anymore. Any thoughts? @FelixErnst 

image
image
image
image

**Comment by TuomasBorman** [comment]
And some other things: 

1. Should `Alpha diversity` and `Beta diversity` be subchapters of `Microbiome exploration`?
2. Some headers are written so that every word starts with uppercase, like `8 Microbiome Community`, some aren't, e.g., `10 Microbiome time series`. This should be consistent

**Comment by ChouaibB** [comment]
1. the separation was related to the closed issue: https://github.com/microbiome/OMA/issues/34
2. Yes I can fix that.

**Review by antagomir — COMMENTED** [review]
The extra material should be only linked in text and not included in side bar. I had asked so in the original comments but good to reiterate. There will be more of such complementary material.

Alpha and beta diversity are vast and very different topics and both deserve their own section. Often they are also used in exploration pääse, we can cite these sections there.

I will have a look at the overall structure in more detalji when getting out of the forests

**Review by antagomir — APPROVED** [review]

**Pull request merged**
