### PR TITLE
Implement bibtex references

### PR DESCRIPTION
**Pull request by RiboRings**
Now rmarkdown links are completely completely with bibtex references.

### CODE REVIEW

**Comment by RiboRings** [comment]
Is there a way to point a link to a specific subsection (not the entire chapter)? I labeled with `bibtexlink` a couple of sites where I should use /@ref(something) instead of a markdown link, but I don't know yet how to link a specific subsection.

**Comment by antagomir** [comment]
Have you just tried to add a bookmark after the subsection title?

Like this. Same as for full chapters.

```
### Assay data {#assaydata}
Section \@ref(assaydata)
```

**Comment by antagomir** [comment]
Thanks!

However: check and resolve conflicts before we can merge.

**Comment by antagomir** [comment]
1) Check that all entries have year info. Another way this error can arise is if one of your BibTeX entries has no year. To find out which entry it is, look earlier in the output for a message like Warning--empty year in ABC2019. So check ABC2019. https://tex.stackexchange.com/questions/54480/package-natbib-error-bibliography-not-compatible-with-author-year-citations

2) There are also cases like "Chao A and Lee SM" in the .bib file. The names should be either "Chao, A" or "A Chao". Check that author entries are fixed for this.

3) Check that all references have the form AuthorYear (with rare exceptions, if justified). For instance, the bibtex key on "alde2016" should be Gloor2016. This has to be changed from both bibtex file as well as the Rmd files.

4) if still does not work, you can try to change bibliography style in index.Rmd "biblio-style: apalike" into something else like "biblio-style: plain" or "biblio-style: abbrv"

**Comment by RiboRings** [comment]
Ok, I got it. Thank you!

**Comment by antagomir** [comment]
@RiboRings can you resolve the failing checks and confirm here that all comments have been taken into account. Then I can merge.

**Comment by antagomir** [comment]
@RiboRings if you could check..?

**Comment by antagomir** [comment]
one more..!

**Comment by antagomir** [comment]
@RiboRings could you resolve the conflicts and sync with master? This seems very good otherwise, just a bit adjustment before we can merge.

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
I synced it with the master but some problems remain. 

It would be easier to troubleshoot when we remove "trivial" problems from the output.

If you have a chance to help to finalize this one, the following can be done:

Warning--I didn't find a database entry for "miaSim2021"
-> means that such entry is missing from the .bib file and should be added

Repeated entry---line 11 of file book.bib
 : @article{Amezquita2020
-> Means that this reference is defined more than once in the bib file and duplicates should be removed/combined

Warning: Package natbib Warning: Citation `Amezquita2020' on page 5 undefined on input line 167.
-> Related to the above double reference and gets solved by removing duplicate references



... and similar comments for the other similar cases.

**Comment by antagomir** [comment]
@RiboRings could you still have a look based on my latest suggestions..?

**Comment by antagomir** [comment]
@RiboRings can we deal with this one and aim to close asap?

**Comment by antagomir** [comment]
The error from GHA:

Quitting from lines 51-55 (23_multi-assay_analyses.Rmd) 
Error: failed to load resource
  name: EH6760
  title: Hintikka XO microbiota counts
  reason: 1 resources failed to download
Execution halted


-> This is trying to download HintikkaXO from microbiomeDataSets online. 

The same data is now also available in the mia package with `data(HintikkaXOData, package="mia")`. 

Could you switch to using that version of the data instead, perhaps we can resolve the error this way?

**Comment by antagomir** [comment]
Check for instance this for possible solution to the GHA failure: 
https://tex.stackexchange.com/questions/54480/package-natbib-error-bibliography-not-compatible-with-author-year-citations

**Comment by RiboRings** [comment]
This is another problem: `Warning:  Citeproc: citation ref not found`.
I think the cross-references to other chapters of the book are not working.

**Comment by antagomir** [comment]
Ah.. right. 

It could be that Aaron Lun had some solutions to this in his [SingleRBook](https://github.com/LTLA/SingleRBook) stuff, not sure. 

Or perhaps Quarto has a better system; we might need to switch to that later anyway. If you can find out if there are possible solutions that would be great but it would also be another PR I guess.

Do we have many cross-refs across sections? If these can be easily removed we could do that for the time being.

**Comment by antagomir** [comment]
Wow - it goes through!

Could we have a quick fix for the citeproc issue, then I could merge this? Rest we can troubleshoot separately later.

**Comment by RiboRings** [comment]
I fixed the citeproc warning too.
It was due to some `@\ref`s that had the forward slash instead of the backslash.

Now it is ready to merge. ✅

**Pull request merged**
