### PR TITLE
Restructure the book

### PR DESCRIPTION
**Pull request by TuomasBorman**
Hello,

https://github.com/microbiome/OMA/issues/352

here is my suggestion for the structure of OMA. You can see the book by extracting the docs zip file, and by opening index.html. Below is the file structure of the book to give some idea of the structure.

[docs.zip](https://github.com/user-attachments/files/16321444/docs.zip)

- part: "Introduction"
      chapters:
        - pages/intro.qmd
        - pages/miaverse.qmd
- part: "Data containers & Importing"
  chapters:
	- pages/containers.qmd
	- pages/import.qmd
	- pages/convert.qmd
- part: "Data Manipulation"
  chapters:
	- pages/wrangling.qmd
	- pages/transformation.qmd
	- pages/taxonomy.qmd
	- pages/agglomeration.qmd
- part: "Exploration & QC"
  chapters:
	- pages/quality_control.qmd
	- pages/composition.qmd
- part: "Diversity & Similarity"
  chapters:
	- pages/alpha_diversity.qmd
	- pages/beta_diversity.qmd
	- pages/clustering.qmd
- part: "Association"
  chapters:
	- pages/differential_abundance.qmd
	- pages/correlation.qmd
	- pages/msea.qmd
	- pages/mmuphin_meta_analysis.qmd
- part: "Networks"
  chapters:
	- pages/network_learning.qmd
	- pages/network_comparison.qmd
- part: "Multiomics"
  chapters:
	- pages/cross_correlation.qmd
	- pages/multiassay_ordination.qmd
	- pages/integrated_learner.qmd
- part: "Machine Learning & Statistical Modeling"
  chapters:
	- pages/machine_learning.qmd
	- pages/statistical_modeling.qmd
- part: "Workflows"
  chapters:
	- pages/introductory_workflow.qmd
	- pages/introductory_workflow_french_version.qmd
	- pages/introductory_workflow_dutch_version.qmd
- part: "Training"
  chapters:
	- pages/training.qmd
	- pages/exercises.qmd
- part: "Support & Resources"
  chapters:
	- pages/support.qmd
	- pages/resources.qmd
	- pages/acknowledgments.qmd
appendices:
- pages/extra_material.qmd
- pages/visualization.qmd
- pages/session_info.qmd

The idea is that the structure is as intuitive and clear as possible allowing us to expand it in the future as needed. Also important point is that the reader should be able to find easily the information needed (there is search option, but that does not help too much if the structure is not clear).

Moreover, I found sections that were repetitive. My plan was to modify the book so that no information was lost. The repetitions made the structure unclear. Now there is linkages between related sections.

Couple points that I made. These things should be fixed or taken into account otherwise:

1. I used callout blocks (note, tip, important and warning). They look quite nice so we could use them more.

2. We could focus more on interpretations as they are something that readers want. They are the hard part which is why we should focus more on them.

3. We use both styles `library(mia)` and `library("mia")`. We should have only one style. I prefer `library("mia")`.

4. In the text, we should harmonize the style of package and function names. Currently, we use several styles. We could have: \`package\`, \`function()\` and \`assay\` slot.

5. Exercises are outdated. Especially RDA exercises as they use vegan directly even though we have simple addRDA() wrapper available.

For the future maintenance, I have also couple points:

1.

We should not exceed 80 characters in line. In the text, it is not that strict but in the code it makes harder to see the code if we have long lines (code does not fit into page correctly). For example, there were this kind of lines quite many

```
long_variable_name <- long_function_name(parameter = "parameter".
                                         parameter2 = "parameter2")
```

Instead I would prefer this kind of lines as it make easier to see the parameters

```
long_variable_name <- long_function_name(
    parameter = "parameter".
    parameter2 = "parameter2"
	)
```

2.

All the chunks should have labels. That is not urgent, but we should take this into account when the code is modified. All modified chunks should have label in the future.

Please see the structure and give feedback. It is much easier to change now than in the future (bigger changes are not probably even possible anymore when the book is established).

-Tuomas

### CODE REVIEW

**Comment by antagomir** [comment]
To me this looks good, no further suggestions at this point.

I like more the style library(mia) than library("mia") as I like it shorter. But can be either one.

Maybe need to open issues about outdated examples and other things that are not feasible to solve as part of the structure update.

The last three items (extra material, visualization, session) could be under appendix chapter, or this is already the idea?

**Comment by TuomasBorman** [comment]
Updated README's contribution instructions and made issues on points that need to be resolved.

library(mia) is fine. My justification was that then `library("mia")` is consistent with `install.packages("mia")`.

Last three sections are already under appendix. My mistake with indentation in the comment above.

Merging when checks are ok.

**Comment by antagomir** [comment]
One more thing to do is to make a quick check on [OSCA](https://bioconductor.org/books/release/OSCA/) and its sub-books for possible inspiration and ideas that we may have overlooked.

**Comment by TuomasBorman** [comment]
I checked the OSCA (and some of the carpentries online book) already for inspiration. Might be good to have other's thoughts also. Moreover, there is room to improve the text. If you have time to do that it would be nice.

**Pull request merged**
