### PR TITLE
Update network chapter and contributors

### PR DESCRIPTION
**Pull request by stefpeschel**
- Reorder network learning chapter to be less nested
- Move network plots to analysis section
- Add comment on closeness centrality
- Add contributors

### CODE REVIEW

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
All other PRs are still against master, so I approve and merge.

**Comment by TuomasBorman** [comment]
> @TuomasBorman do we take the PRs still against the master branch directly? just to check before I merge.

Sorry for delay. --> Yes, I think that we can still use master since we have used it already previously. But after the next Bioc release, let's use devel branch (also in mia packages)

**Comment by TuomasBorman** [comment]
In general, we should follow Bioc suggestions/rules as closely as possible (separate devel branch is one of those)

**Comment by antagomir** [comment]
Yes!

**Pull request merged**
