### PR TITLE
#471: Update MgnifyR link

### PR DESCRIPTION
**Pull request by 0xMuluh**
ping #353 #471 
 Add MGnifyR Bioconductor information

### CODE REVIEW

**Comment by antagomir** [comment]
Is this PR OK? The entire section on containers has been deleted, when the idea was to update a single line linking to MGnify?

**Comment by 0xMuluh** [comment]
Yes the PR is okay. I am surprised as well because I changed only a single line. Maybe it has something to do with GHA. 
See[ file change](https://github.com/microbiome/OMA/pull/472/files). From attachment, the highlight indi
updatelink
cates the changes.

**Comment by TuomasBorman** [comment]
I am not sure what is causing this. Btw, do you have access directly to OMA. You could do modifications directly to OMA's branch so it is usually easier to review (I can run it locally)

--> You could also do it now. And close this PR

**Comment by 0xMuluh** [comment]
I don't have permission to repo. However as i have realized, the total file change is as a result of line endings.(lf, crlf)

**Comment by 0xMuluh** [comment]
I will close the PR now and wait for access.

**Comment by TuomasBorman** [comment]
Now you should have access

**Pull request closed without merging**
