### PR TITLE
Add: missing packages to DESCRIPTION

### PR DESCRIPTION
**Pull request by artur-sannikov**
Packages `SuperLearner`, `cowplot`, and `scuttles` were missing from the `DESCRIPTION` file.

### CODE REVIEW

**Comment by TuomasBorman** [comment]
Are `SuperLearner` and `cowplot` needed? They are not directly used in the book, they are just dependencies of `IntegratedLearner`.  The package does not use correctly the dependencies and hopefully it will be fixed soon

**Comment by artur-sannikov** [comment]
When I was building the book, it said that these dependencies are missing.

**Comment by antagomir** [comment]
Shall we merge this for now, if this is a practical problem? For me OK to merge.

Or do we convert this into an issue to be checked later and close this PR for the time being?

**Comment by TuomasBorman** [comment]
It seems that the book is building correctly in GHA

**Comment by TuomasBorman** [comment]
What command did you use to build the book. These packages should already come with other packages. I am fine with this PR, but managing this many packages is challenging and we might have troubles in Bioc submission

**Comment by artur-sannikov** [comment]
It's complaining about these packages at the `BiocBook::preview(BiocBook::BiocBook('.'))` stage.

```
> BiocBook::preview(BiocBook::BiocBook('.'))
✖ Some dependencies found in book pages are not listed in DESCRIPTION: 
  • SuperLearner
  • cowplot
  • scuttle
ℹ Consider adding these dependencies to DESCRIPTION
```

If it builds fine, however, we can close this PR.

**Comment by TuomasBorman** [comment]
Alright, I think it is fine adding these. I am not sure when IntegratedLearner will be fixed anyways. I can check these dependencies later that all are really needed. Thanks!

**Pull request merged**
