### PR TITLE
Quarto conversion 

### PR DESCRIPTION
**Pull request by ake123**
Consider Quarto as the basis for the final book version #188

### CODE REVIEW

**Review by antagomir — APPROVED** [review]
OK to me if the book renders and publishes correctly, and README has up-to-date instructions on how to render & view locally.

**Comment by ake123** [comment]
README file is created  specifically for Quarto conversion and can be found in  `README_quarto_conversion.md` file.

**Comment by antagomir** [comment]
It seems that we will unfortunately have to cancel this PR in the end, because the BiocBook conversion appeared in parallel in #376 .. but let us wait until that is merged, in case there are any changes.

**Comment by antagomir** [comment]
Replaced by #379

**Pull request closed without merging**
